spring.datasource.url=jdbc:postgresql://localhost:5432/gdu_jpa_lab
spring.datasource.username=postgres
spring.datasource.password=${Sun.cheese15:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
