spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/clinic_management}
    username: ${DB_USERNAME:clinic_app}
    password: ${DB_PASSWORD:is required}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false

logging:
  level:
    root: INFO
